### get all users
GET http://localhost:8888/users

### get user by id
GET http://localhost:8888/users/1

### add user
POST http://localhost:8888/users
Content-Type: application/json

{
  "full_name": "no name",
  "email": "admin@mailcom",
  "password": "admin#123",
  "address": "Mahasaraja Depok",
  "phone": "08123456789",
  "pictures": "images/path/picture.jpg"
}

### edit user
PATCH http://localhost:8888/users/1
Content-Type: application/json

{
  "full_name": "aDMIN",
  "email": "bukanadmin@mailcom",
  "password": "admin#123ABC",
  "address": "Maharaja Depok",
  "phone": "08123456710",
  "pictures": "images/path/pictureu.jpg",
}

### delete user by id
DELETE http://localhost:8888/users/11

	# r.GET("/", h.Home)
	# r.GET("/users/:id", h.GetUserById)
	# r.POST("/users", h.AddUser)
	# r.PATCH("/users/:id", h.UpdateUser)
	# r.DELETE("/users/:id", h.DeleteUser)

###
# {
#   "product_name": "test from api",
#   "product_desc": "product_desc",
#   "price": 1001,
#   "quantity": 5,
#   "discount" : 1
# }
