# http test
## users

### get all users
GET http://localhost:8888/users

### get user by id
GET http://localhost:8888/users/1

### add user
POST http://localhost:8888/users
Content-Type: application/json

{
  "full_name": "no name",
  "email": "admin@mailcom",
  "password": "admin#123",
  "address": "Mahasaraja Depok",
  "phone": "08123456789",
  "pictures": "images/path/picture.jpg"
}

### edit user
PATCH http://localhost:8888/users/1
Content-Type: application/json

{
  "full_name": "aDMIN",
  "email": "bukanadmin@mailcom",
  "password": "admin#123ABC",
  "address": "Maharaja Depok",
  "phone": "08123456710",
  "pictures": "images/path/pictureu.jpg",
}

### delete user by id
DELETE http://localhost:8888/users/11

## products 

### get all product
GET http://localhost:8888/admin/products

### get product by id
GET http://localhost:8888/admin/products/1

### add products
POST http://localhost:8888/admin/products
Content-Type: application/json

{
  "product_name": "juice",
  "product_desc": "Juice Flavour",
  "price":   10000,
  "quantity":100,
  "discount":1000,
}

### edit product
PATCH http://localhost:8888/admin/products/1
Content-Type: application/json

{
  "product_name": "Water",
  "product_desc": "Mineral Water",
  "price":   1000,
  "quantity":240,
  "discount":1000,
}

### delete product by id
DELETE http://localhost:8888/admin/products/11

## category

### get all category
GET http://localhost:8888/admin/category

### get category by id
GET http://localhost:8888/admin/category/1

### add category
POST http://localhost:8888/admin/category
Content-Type: application/json

{
  "category_name": "no name"
}

### edit category
PATCH http://localhost:8888/admin/category/1
Content-Type: application/json

{
  "category_name": "food"
}

### delete category by id
DELETE http://localhost:8888/admin/category/11

## auth

### register
# "INSERT INTO users(full_name, email,password) VALUES($1,$2,$3) RETURNING (full_name, email", user.Email, user.Password, user.Full_Name,
POST http://localhost:8888/register 
Content-Type: application/json

{
  "full_name": "juice",
  "email": "juiceflavour@mail.com",
  "password":   "10000"
}

# "Success": false,
# "Message": "Bad Request 400 input the data correctly:json: cannot unmarshal number into Go struct field AuthRegister.password of type string",
# "Results": null

## product cart

### add to cart
POST http://localhost:8888/detailproduct/addcart
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 2,
  "product_name": "Juice",
  "base_price": 10000
}
