basePath: /api/v1
definitions:
  models.Product:
    properties:
      discount:
        type: integer
      id:
        type: integer
      price:
        type: integer
      product_desc:
        type: string
      product_name:
        type: string
      quantity:
        type: integer
    type: object
  models.Response:
    properties:
      message:
        type: string
      results: {}
      success:
        type: boolean
    type: object
  models.Users:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      phone:
        type: string
      pictures:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: coffe shop project
  title: Coffee Shop API
  version: 1.0.0
paths:
  /:
    get:
      consumes:
      - application/json
      description: Retrieve all products from the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get All Product
      tags:
      - products
  /admin/products:
    post:
      consumes:
      - application/json
      description: Add a new product to the system
      parameters:
      - description: Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Add Product
      tags:
      - products
  /browseproduct:
    get:
      consumes:
      - application/json
      description: Retrieve Browse Product from the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Browse Product
      tags:
      - products
  /products/home:
    get:
      consumes:
      - application/json
      description: Retrieve Product Home from the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Product Home
      tags:
      - products
  /products/reviews:
    get:
      consumes:
      - application/json
      description: Retrieve Product Reviews from the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Product Reviews
      tags:
      - products
  /users:
    post:
      consumes:
      - application/json
      description: AddUser Process
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Users'
      summary: AddUser Post
      tags:
      - users
  /users/{id}:
    delete:
      description: Delete user by ID
      parameters:
      - description: User ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Retrieve a single user by its ID parameter
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
